// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addCommentEditor': string;
  'textareaHolder': string;
}
export const cssExports: CssExports;
export default cssExports;
