// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'checkbox': string;
  'checkboxCircle': string;
  'content': string;
  'contentDetails': string;
  'contentDetailsHeader': string;
  'contentDetailsOverview': string;
  'contentDetailsParentIcon': string;
  'contentDetailsParentInfo': string;
  'contentDetailsParentLink': string;
  'contentDetailsParentName': string;
  'date': string;
  'dateOverdue': string;
  'dueControls': string;
  'itemOverviewContent': string;
  'itemOverviewDescription': string;
  'itemOverviewFooter': string;
  'itemOverviewHeader': string;
  'itemOverviewMain': string;
  'itemOverviewSub': string;
  'taskContent': string;
  'taskDetailsModal': string;
}
export const cssExports: CssExports;
export default cssExports;
