// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'count': string;
  'leftControl': string;
  'postLoginHeader': string;
  'rightControl': string;
  'searchWrapper': string;
  'topBar': string;
  'topbarBtn': string;
}
export const cssExports: CssExports;
export default cssExports;
