// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionItem': string;
  'commentActions': string;
  'commentContent': string;
  'commentItem': string;
  'commentMeta': string;
  'commentsContainer': string;
  'commentsListContainer': string;
  'commentsTab': string;
  'emptyIllsutration': string;
  'emptyState': string;
  'emptyStateBody': string;
  'time': string;
  'username': string;
}
export const cssExports: CssExports;
export default cssExports;
