// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loginForm': string;
  'loginFormHeader': string;
  'loginFormLogo': string;
  'loginPage': string;
  'moveToSignCta': string;
  'note': string;
  'seperator': string;
}
export const cssExports: CssExports;
export default cssExports;
