// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'fadein': string;
  'modal-appear': string;
  'modal-disappear': string;
  'modalContent': string;
  'modalWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
