// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionItem': string;
  'active': string;
  'checkbox': string;
  'checkboxCircle': string;
  'contentWrapper': string;
  'date': string;
  'dateOverdue': string;
  'dueControls': string;
  'infoFlags': string;
  'project': string;
  'taskContent': string;
  'taskDescription': string;
  'taskItem': string;
  'taskItemActions': string;
  'taskItemBody': string;
  'taskItemContent': string;
}
export const cssExports: CssExports;
export default cssExports;
