// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addTaskButton': string;
  'addTaskEditor': string;
  'buttonContainer': string;
  'descriptionField': string;
  'editingArea': string;
  'editorFormActions': string;
  'inputFields': string;
  'titleField': string;
}
export const cssExports: CssExports;
export default cssExports;
