// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'items': string;
  'listHolder': string;
  'rescheduleMenuButton': string;
  'sectionContentTop': string;
  'sectionContentTopActions': string;
  'singleSection': string;
}
export const cssExports: CssExports;
export default cssExports;
