// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionLabel': string;
  'actions': string;
  'allTasksPage': string;
  'emptyListHolder': string;
  'emptyListIllustration': string;
  'emptyStateBody': string;
  'emptyStateButton': string;
  'emptyStateHeader': string;
  'headerContent': string;
  'sectionContent': string;
  'sectionHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
