// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'moveToLoginCta': string;
  'note': string;
  'seperator': string;
  'signupForm': string;
  'signupFormField': string;
  'signupFormHeader': string;
  'signupFormLogo': string;
  'signupPage': string;
}
export const cssExports: CssExports;
export default cssExports;
