// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'headerOptions': string;
  'option': string;
}
export const cssExports: CssExports;
export default cssExports;
