// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'appSidebar': string;
  'hideSidebar': string;
  'iconHolder': string;
  'itemContent': string;
  'itemCounter': string;
  'sidebarContent': string;
}
export const cssExports: CssExports;
export default cssExports;
