// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appLayout': string;
  'appLayoutWrapper': string;
  'effect-fade-in': string;
  'mainContent': string;
  'moveLeft': string;
}
export const cssExports: CssExports;
export default cssExports;
