// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsContainer': string;
  'addTaskModal': string;
  'editingArea': string;
  'formActions': string;
  'inputFields': string;
  'modalBody': string;
  'textAreaWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
